### ISSUE TITLE
am i doing something wrong? this throws an error.

### ISSUE THREAD

**Issue by fahadbilal** [didierfranc/gatsby-plugin-google-fonts#1]
WebpackError: Unexpected token import

module.exports = {
  siteMetadata: {
    title: `HybridCapital`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-sass`,
    {
      resolve: `gatsby-plugin-google-fonts`,
      options: {
        fonts: [`limelight`, `source sans`]
      }
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/pages`,
        name: `pages`,
      }
    },
    'gatsby-transformer-remark'
  ],
}

**Comment by resir014** [comment]
@fahadbilal Seems like @didierfranc changed the entry point of the plugin to `gatsby-ssr.js`, but forgot to change the `main` part of the `package.json`!

PR coming right up.

**Comment by didierfranc** [comment]
Probably es6 I'm checking that

**Comment by resir014** [comment]
Hey @didierfranc,

Node v8.4.0 and Gatsby CLI v1.1.6. Still the same error atm.

**Comment by didierfranc** [comment]
I released a new version with an es5 build this must be better ;)

**Comment by resir014** [comment]
@didierfranc Aweome, it works now. Thank you!
