### ISSUE TITLE
Support for font weights

### ISSUE THREAD

**Issue by dalbinaco** [didierfranc/gatsby-plugin-google-fonts#3]
Is there any way to specify font weights? I'm trying to use `font-weight: 900` but it seems like it's going up to just 700.

**Comment by dalbinaco** [comment]
Got it. Just add the font weights after the font name, like: 

```javascript
fonts: [
   `montserrat`, `montserrat\:700`, `montserrat\:900`, `open sans`
  ]
```

**Comment by didierfranc** [comment]
Great tip !

**Comment by kodepareek** [comment]
Hi. How can I add the font style in the above syntax? Trying to inject Heebo into the mix and on inspecting the header I can only see that the plugin is requesting different font weights but only 1 font style - normal. 

```
          fonts: [
            'heebo\:normal', 'heebo\:medium', 'heebo\:bold', 'heebo\:light',
          ]

```
This is what my gatsby config looks like.

**Comment by rohittagadiya** [comment]
> Got it. Just add the font weights after the font name, like:
> 
> ```js
> fonts: [
>    `montserrat`, `montserrat\:700`, `montserrat\:900`, `open sans`
>   ]
> ```

This works for me!
Thanks
