### ISSUE TITLE
Support WebFontLoader

### ISSUE THREAD

**Issue by sloria** [didierfranc/gatsby-plugin-google-fonts#5]
Using [WebFontLoader](https://github.com/typekit/webfontloader) is the recommended way to load web fonts (see [here](https://prowebtype.com/delivering-web-fonts/#webfontloader) and [here](http://typographyhandbook.com/#font-loading)).

It would be great if this plugin could inject the proper code for WebFontLoader.

**Comment by gilesbutler** [comment]
I agree it's the recommended way but something else to consider... it also has an effect on the time it takes for the page to become interactive. Plus on iOS and in some webkit browser you can get a flash of un-styled text.

Just some considerations to make before switching :)

**Comment by kennedyrose** [comment]
I've made a separate plugin to support async loading of fonts via webfontloader. This should take care of this request.

https://www.npmjs.com/package/gatsby-plugin-web-font-loader

**Comment by didierfranc** [comment]
👍
